DATA:
  IMG_SIZE: 224

MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.0
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"

  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    PATCH_SIZE: 4
    IN_CHANS: 3
    EMBED_DIM: 96
    DEPTHS: [2, 2, 2, 2]
    DECODER_DEPTHS: [2, 2, 2, 1]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    MLP_RATIO: 4.0
    QKV_BIAS: true
    QK_SCALE: null
    APE: false
    PATCH_NORM: true

TRAIN:
  USE_CHECKPOINT: false
